// Copyright 2021 Evgeny Safonov
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-03-03 16:38:34.833588 +0000 UTC

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

// HTTPVerb is documented here http://hl7.org/fhir/ValueSet/http-verb
type HTTPVerb int

const (
	HTTPVerbGET HTTPVerb = iota
	HTTPVerbHEAD
	HTTPVerbPOST
	HTTPVerbPUT
	HTTPVerbDELETE
	HTTPVerbPATCH
)

func (code HTTPVerb) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *HTTPVerb) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "GET":
		*code = HTTPVerbGET
	case "HEAD":
		*code = HTTPVerbHEAD
	case "POST":
		*code = HTTPVerbPOST
	case "PUT":
		*code = HTTPVerbPUT
	case "DELETE":
		*code = HTTPVerbDELETE
	case "PATCH":
		*code = HTTPVerbPATCH
	default:
		return fmt.Errorf("unknown HTTPVerb code `%s`", s)
	}
	return nil
}
func (code HTTPVerb) String() string {
	return code.Code()
}
func (code HTTPVerb) Code() string {
	switch code {
	case HTTPVerbGET:
		return "GET"
	case HTTPVerbHEAD:
		return "HEAD"
	case HTTPVerbPOST:
		return "POST"
	case HTTPVerbPUT:
		return "PUT"
	case HTTPVerbDELETE:
		return "DELETE"
	case HTTPVerbPATCH:
		return "PATCH"
	}
	return "<unknown>"
}
func (code HTTPVerb) Display() string {
	switch code {
	case HTTPVerbGET:
		return "GET"
	case HTTPVerbHEAD:
		return "HEAD"
	case HTTPVerbPOST:
		return "POST"
	case HTTPVerbPUT:
		return "PUT"
	case HTTPVerbDELETE:
		return "DELETE"
	case HTTPVerbPATCH:
		return "PATCH"
	}
	return "<unknown>"
}
func (code HTTPVerb) Definition() string {
	switch code {
	case HTTPVerbGET:
		return "HTTP GET Command."
	case HTTPVerbHEAD:
		return "HTTP HEAD Command."
	case HTTPVerbPOST:
		return "HTTP POST Command."
	case HTTPVerbPUT:
		return "HTTP PUT Command."
	case HTTPVerbDELETE:
		return "HTTP DELETE Command."
	case HTTPVerbPATCH:
		return "HTTP PATCH Command."
	}
	return "<unknown>"
}
