// Copyright 2021
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-03-08 09:41:02.954082 +0000 UTC

package models

// Meta is documented here http://hl7.org/fhir/StructureDefinition/Meta
type Meta struct {
	ID          *string     `bson:"id,omitempty" json:"id,omitempty"`
	Extension   []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	VersionId   *string     `bson:"versionId,omitempty" json:"versionId,omitempty"`
	LastUpdated *string     `bson:"lastUpdated,omitempty" json:"lastUpdated,omitempty"`
	Source      *string     `bson:"source,omitempty" json:"source,omitempty"`
	Profile     []string    `bson:"profile,omitempty" json:"profile,omitempty"`
	Security    []Coding    `bson:"security,omitempty" json:"security,omitempty"`
	Tag         []Coding    `bson:"tag,omitempty" json:"tag,omitempty"`
}
