// Copyright 2021 Evgeny Safonov
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-03-03 16:38:34.755489 +0000 UTC

package models

// ParameterDefinition is documented here http://hl7.org/fhir/StructureDefinition/ParameterDefinition
type ParameterDefinition struct {
	ID            *string               `bson:"id,omitempty" json:"id,omitempty"`
	Extension     []Extension           `bson:"extension,omitempty" json:"extension,omitempty"`
	Name          *string               `bson:"name,omitempty" json:"name,omitempty"`
	Use           OperationParameterUse `bson:"use" json:"use"`
	Min           *int                  `bson:"min,omitempty" json:"min,omitempty"`
	Max           *string               `bson:"max,omitempty" json:"max,omitempty"`
	Documentation *string               `bson:"documentation,omitempty" json:"documentation,omitempty"`
	Type          string                `bson:"type" json:"type"`
	Profile       *string               `bson:"profile,omitempty" json:"profile,omitempty"`
}
