// Copyright 2021 Evgeny Safonov
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-03-03 16:38:34.555234 +0000 UTC

package models

import "encoding/json"

// Resource is documented here http://hl7.org/fhir/StructureDefinition/Resource
type Resource struct {
	ID            *string `bson:"id,omitempty" json:"id,omitempty"`
	Meta          *Meta   `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules *string `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language      *string `bson:"language,omitempty" json:"language,omitempty"`
}
type OtherResource Resource

// MarshalJSON marshals the given Resource as JSON into a byte slice
func (r Resource) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherResource
		ResourceType string `json:"resourceType"`
	}{
		OtherResource: OtherResource(r),
		ResourceType:  "Resource",
	})
}

// UnmarshalResource unmarshals a Resource.
func UnmarshalResource(b []byte) (Resource, error) {
	var resource Resource
	if err := json.Unmarshal(b, &resource); err != nil {
		return resource, err
	}
	return resource, nil
}
